param([string]$SdkRoot = 'C:\Program Files (x86)\Android\android-sdk', [switch]$Offline, [switch]$Full)
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
Push-Location $projectRoot
try {
    # Public AOSP test keys match this user-supplied APK's certificate exactly.
    # No production/private user key is read or generated by this script.
    if (!(Test-Path 'build/signing/testkey.pk8') -or !(Test-Path 'build/signing/testkey.x509.pem')) {
        throw 'AOSP public test key files missing; see PRACTICE-README.txt for provenance.'
    }
    if ($Offline -and $Full) { throw 'Choose either Offline or Full, not both.' }
    $variant = if ($Full) { 'arcaea-full-offline-practice' } elseif ($Offline) { 'arcaea-offline-practice' } else { 'arcaea-practice' }
    $finalApk = if ($Full) { 'arcaea-full-offline-practice-arm64-fix4.apk' } elseif ($Offline) { 'arcaea-offline-practice-arm64-fix1.apk' } else { 'arcaea-practice-arm64-test.apk' }
    [string[]]$packageArgs = @()
    if ($Offline) { $packageArgs += '--offline' }
    if ($Full) { & python tools/package_full_apk.py }
    else { & python tools/package_apk.py @packageArgs }
    if ($LASTEXITCODE -ne 0) { throw 'APK packaging failed' }
    $align = Join-Path $SdkRoot 'build-tools/34.0.0/zipalign.exe'
    & $align -f 4 "build/$variant-unsigned.apk" "build/$variant-aligned.apk"
    if ($LASTEXITCODE -ne 0) { throw 'APK alignment failed' }
    $signer = Join-Path $SdkRoot 'build-tools/34.0.0/lib/apksigner.jar'
    & java -Xmx2g -jar $signer sign --key build/signing/testkey.pk8 --cert build/signing/testkey.x509.pem --v1-signing-enabled true --v2-signing-enabled true --v3-signing-enabled true --v4-signing-enabled false --out $finalApk "build/$variant-aligned.apk"
    if ($LASTEXITCODE -ne 0) { throw 'APK signing failed' }
    & java -jar $signer verify --verbose --print-certs $finalApk
    if ($LASTEXITCODE -ne 0) { throw 'APK signature verification failed' }
    & $align -c 4 $finalApk
    if ($LASTEXITCODE -ne 0) { throw 'Final APK alignment verification failed' }
} finally { Pop-Location }
